### ISSUE TITLE
Program is looking for "index.html" in every file/directory of input folder 

### ISSUE THREAD

**Issue by smajor01** [LanGerdej/antismash_to_csv#1]
Hello!

This looked like a really nice tool to try and summarize output from antiSMASH for easier manipulations. However, it will not run because it is looking for index.html everywhere. I've attached the error traceback proceeding my input command.

```
python3 ../../scripts/antismash_to_csv-main/antismash_to_csv-main/antismash_to_csv.py -in deepBGC-antiSMASH_OXR-9_final_assembly/ -out deepBGC-antiSMASH_OXR-9_final_assembly/ -name OXR-9_deep-antismash.csv

Traceback (most recent call last):
  File "/mnt/c/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-9/../../scripts/antismash_to_csv-main/antismash_to_csv-main/antismash_to_csv.py", line 123, in <module>
    main()
  File "/mnt/c/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-9/../../scripts/antismash_to_csv-main/antismash_to_csv-main/antismash_to_csv.py", line 120, in main
    args.func(args)
  File "/mnt/c/Users/SamuelMajor/OneDrive - Gloucester Marine Genomics Institute/Desktop/OXR genomes/OXR-9/../../scripts/antismash_to_csv-main/antismash_to_csv-main/antismash_to_csv.py", line 24, in run
    soup = BeautifulSoup(open(f'{sequence}/index.html'), 'html.parser')
NotADirectoryError: [Errno 20] Not a directory: 'deepBGC-antiSMASH_OXR-9_final_assembly/bacteria-17583fbc-9870-484e-878d-101529d126d6.log/index.html'
```

**Comment by LanGerdej** [comment]
Hi, thanks for your feedback. 
I think the issue is with the -in path. You should provide the path to a directory, that exclusively contains folders that are antismash results. It shouldn't contain any other files such as "bacteria-17583fbc-9870-484e-878d-101529d126d6.log". It should only contain folders that are a direct result of antismash (each such result folder should contain index.html, since antismash outputs it in each result).
The program will look inside the provided directory and check each folder in this directory for its index.html, scrape the important data and output it in a .csv form. If there are folders that don't contain index.html (which should be inside every antismash result), the above error will be returned.
I hope this helps, if you have any further questions or feedback please let me know.

Lan
